'use client';

import { FoundationList } from './foundation-list';

type Field = { key: string; label: string; required?: boolean; type?: 'text' | 'number' | 'date' };
type Config = { title: string; objectCode: string; code: string; name: string; fields: Field[] };

const base = (title: string, objectCode: string, code: string, name: string, fields: Field[]): Config => ({ title, objectCode, code, name, fields });

const configs: Record<string, Config> = {
  countries: base('Countries','COUNTRY','countryCode','countryName',[{key:'countryCode',label:'Country Code',required:true},{key:'countryName',label:'Country Name',required:true},{key:'isoAlpha2',label:'ISO Alpha-2',required:true},{key:'isoAlpha3',label:'ISO Alpha-3',required:true},{key:'phoneCode',label:'Phone Code'}]),
  states: base('States / Provinces','STATE','stateCode','stateName',[{key:'countryId',label:'Country ID',required:true},{key:'stateCode',label:'State Code',required:true},{key:'stateName',label:'State Name',required:true}]),
  cities: base('Cities','CITY','cityCode','cityName',[{key:'countryId',label:'Country ID',required:true},{key:'stateId',label:'State ID'},{key:'cityCode',label:'City Code',required:true},{key:'cityName',label:'City Name',required:true}]),
  territories: base('Territories','TERRITORY','territoryCode','territoryName',[{key:'companyId',label:'Company ID'},{key:'parentTerritoryId',label:'Parent Territory ID'},{key:'territoryCode',label:'Territory Code',required:true},{key:'territoryName',label:'Territory Name',required:true},{key:'territoryType',label:'Territory Type',required:true}]),
  uom: base('Units of Measure','UNIT_OF_MEASURE','uomCode','uomName',[{key:'uomCode',label:'UOM Code',required:true},{key:'uomName',label:'UOM Name',required:true},{key:'uomCategory',label:'Category',required:true},{key:'symbol',label:'Symbol',required:true},{key:'decimalPrecision',label:'Decimal Precision',type:'number'}]),
  'uom-conversions': base('UOM Conversions','UOM_CONVERSION','fromUomId','toUomId',[{key:'itemId',label:'Item ID'},{key:'fromUomId',label:'From UOM ID',required:true},{key:'toUomId',label:'To UOM ID',required:true},{key:'conversionFactor',label:'Conversion Factor',required:true,type:'number'},{key:'effectiveFrom',label:'Effective From',type:'date'}]),
  'item-groups': base('Item Groups','ITEM_GROUP','itemGroupCode','itemGroupName',[{key:'companyId',label:'Company ID'},{key:'parentItemGroupId',label:'Parent Group ID'},{key:'itemGroupCode',label:'Group Code',required:true},{key:'itemGroupName',label:'Group Name',required:true},{key:'description',label:'Description'}]),
  'item-categories': base('Item Categories','ITEM_CATEGORY','itemCategoryCode','itemCategoryName',[{key:'companyId',label:'Company ID'},{key:'parentItemCategoryId',label:'Parent Category ID'},{key:'itemCategoryCode',label:'Category Code',required:true},{key:'itemCategoryName',label:'Category Name',required:true},{key:'categoryType',label:'Category Type',required:true}]),
  'item-attributes': base('Item Attributes','ITEM_ATTRIBUTE_DEFINITION','attributeCode','attributeName',[{key:'attributeCode',label:'Attribute Code',required:true},{key:'attributeName',label:'Attribute Name',required:true},{key:'dataType',label:'Data Type',required:true},{key:'unitOfMeasureId',label:'UOM ID'}]),
  brands: base('Brands','BRAND','brandCode','brandName',[{key:'brandCode',label:'Brand Code',required:true},{key:'brandName',label:'Brand Name',required:true},{key:'manufacturerId',label:'Manufacturer ID'}]),
  manufacturers: base('Manufacturers','MANUFACTURER','manufacturerCode','manufacturerName',[{key:'manufacturerCode',label:'Manufacturer Code',required:true},{key:'manufacturerName',label:'Manufacturer Name',required:true},{key:'countryId',label:'Country ID'},{key:'website',label:'Website'}]),
  items: base('Items','ITEM','itemCode','name',[{key:'companyId',label:'Company ID',required:true},{key:'itemCode',label:'Item Code',required:true},{key:'name',label:'Item Name',required:true},{key:'itemType',label:'Item Type',required:true},{key:'itemGroupId',label:'Item Group ID',required:true},{key:'itemCategoryId',label:'Item Category ID',required:true},{key:'baseUomId',label:'Base UOM ID',required:true},{key:'stockUomId',label:'Stock UOM ID',required:true},{key:'uom',label:'Legacy UOM Code',required:true},{key:'manufacturingStrategy',label:'Manufacturing Strategy',required:true},{key:'replenishmentPolicy',label:'Replenishment Policy',required:true},{key:'trackingMethod',label:'Tracking Method',required:true}]),
  warehouses: base('Warehouses','WAREHOUSE','code','name',[{key:'companyId',label:'Company ID',required:true},{key:'branchId',label:'Branch ID'},{key:'plantId',label:'Plant ID'},{key:'parentWarehouseId',label:'Parent Warehouse ID'},{key:'code',label:'Warehouse Code',required:true},{key:'name',label:'Warehouse Name',required:true},{key:'warehouseType',label:'Warehouse Type',required:true}]),
  'warehouse-zones': base('Warehouse Zones','WAREHOUSE_ZONE','zoneCode','zoneName',[{key:'warehouseId',label:'Warehouse ID',required:true},{key:'parentZoneId',label:'Parent Zone ID'},{key:'zoneCode',label:'Zone Code',required:true},{key:'zoneName',label:'Zone Name',required:true},{key:'zoneType',label:'Zone Type',required:true}]),
  bins: base('Bins','BIN','binCode','binName',[{key:'warehouseId',label:'Warehouse ID',required:true},{key:'warehouseZoneId',label:'Zone ID'},{key:'binCode',label:'Bin Code',required:true},{key:'binName',label:'Bin Name',required:true},{key:'binType',label:'Bin Type',required:true}]),
  'stock-statuses': base('Stock Statuses','STOCK_STATUS','statusCode','statusName',[{key:'statusCode',label:'Status Code',required:true},{key:'statusName',label:'Status Name',required:true}]),
  batches: base('Batches','BATCH','batchNumber','qualityStatus',[{key:'companyId',label:'Company ID',required:true},{key:'itemId',label:'Item ID',required:true},{key:'batchNumber',label:'Batch Number',required:true},{key:'manufacturingDate',label:'Manufacturing Date',type:'date'},{key:'expiryDate',label:'Expiry Date',type:'date'},{key:'qualityStatus',label:'Quality Status'}]),
  'serial-numbers': base('Serial Numbers','SERIAL_NUMBER','serialNumber','lifecycleStatus',[{key:'companyId',label:'Company ID',required:true},{key:'itemId',label:'Item ID',required:true},{key:'serialNumber',label:'Serial Number',required:true},{key:'batchId',label:'Batch ID'},{key:'lifecycleStatus',label:'Lifecycle Status'}]),
  'business-partners': base('Business Partners','BUSINESS_PARTNER','partnerCode','partnerName',[{key:'companyId',label:'Company ID'},{key:'partnerCode',label:'Partner Code',required:true},{key:'partnerName',label:'Partner Name',required:true},{key:'partnerType',label:'Partner Type',required:true},{key:'countryId',label:'Country ID'},{key:'defaultCurrencyId',label:'Currency ID'}]),
  customers: base('Customers','CUSTOMER','code','name',[{key:'companyId',label:'Company ID',required:true},{key:'businessPartnerId',label:'Business Partner ID',required:true},{key:'code',label:'Customer Code',required:true},{key:'name',label:'Customer Name',required:true},{key:'creditLimit',label:'Credit Limit',type:'number'}]),
  suppliers: base('Suppliers','SUPPLIER','code','name',[{key:'companyId',label:'Company ID',required:true},{key:'businessPartnerId',label:'Business Partner ID',required:true},{key:'code',label:'Supplier Code',required:true},{key:'name',label:'Supplier Name',required:true},{key:'supplierRating',label:'Supplier Rating',type:'number'}]),
  'customer-groups': base('Customer Groups','CUSTOMER_GROUP','customerGroupCode','customerGroupName',[{key:'companyId',label:'Company ID'},{key:'parentCustomerGroupId',label:'Parent Group ID'},{key:'customerGroupCode',label:'Group Code',required:true},{key:'customerGroupName',label:'Group Name',required:true}]),
  'supplier-groups': base('Supplier Groups','SUPPLIER_GROUP','supplierGroupCode','supplierGroupName',[{key:'companyId',label:'Company ID'},{key:'parentSupplierGroupId',label:'Parent Group ID'},{key:'supplierGroupCode',label:'Group Code',required:true},{key:'supplierGroupName',label:'Group Name',required:true}]),
  addresses: base('Addresses','ADDRESS','addressType','addressLine1',[{key:'companyId',label:'Company ID'},{key:'addressType',label:'Address Type',required:true},{key:'addressLine1',label:'Address Line 1',required:true},{key:'countryId',label:'Country ID',required:true},{key:'stateId',label:'State ID'},{key:'cityId',label:'City ID'},{key:'postalCode',label:'Postal Code'}]),
  contacts: base('Contact Persons','CONTACT_PERSON','displayName','email',[{key:'firstName',label:'First Name',required:true},{key:'lastName',label:'Last Name'},{key:'displayName',label:'Display Name',required:true},{key:'email',label:'Email'},{key:'mobile',label:'Mobile'}]),
  'payment-terms': base('Payment Terms','PAYMENT_TERM','paymentTermCode','paymentTermName',[{key:'paymentTermCode',label:'Term Code',required:true},{key:'paymentTermName',label:'Term Name',required:true},{key:'dueDays',label:'Due Days',required:true,type:'number'},{key:'dueDateCalculation',label:'Due Date Calculation',required:true}]),
  'credit-terms': base('Credit Terms','CREDIT_TERM','creditTermCode','creditTermName',[{key:'creditTermCode',label:'Term Code',required:true},{key:'creditTermName',label:'Term Name',required:true},{key:'creditDays',label:'Credit Days',required:true,type:'number'},{key:'graceDays',label:'Grace Days',type:'number'}]),
  'credit-profiles': base('Credit Profiles','CREDIT_PROFILE','businessPartnerId','riskRating',[{key:'companyId',label:'Company ID',required:true},{key:'businessPartnerId',label:'Business Partner ID',required:true},{key:'creditTermId',label:'Credit Term ID',required:true},{key:'creditLimit',label:'Credit Limit',required:true,type:'number'},{key:'riskRating',label:'Risk Rating'}]),
  'delivery-terms': base('Delivery Terms','DELIVERY_TERM','deliveryTermCode','deliveryTermName',[{key:'deliveryTermCode',label:'Term Code',required:true},{key:'deliveryTermName',label:'Term Name',required:true},{key:'description',label:'Description'}]),
  incoterms: base('Incoterms','INCOTERM','incotermCode','incotermName',[{key:'incotermCode',label:'Incoterm Code',required:true},{key:'incotermName',label:'Incoterm Name',required:true},{key:'versionYear',label:'Version Year',required:true,type:'number'}]),
  'price-lists': base('Price Lists','PRICE_LIST','priceListCode','priceListName',[{key:'companyId',label:'Company ID'},{key:'priceListCode',label:'Price List Code',required:true},{key:'priceListName',label:'Price List Name',required:true},{key:'currencyId',label:'Currency ID',required:true},{key:'priceListType',label:'Price List Type',required:true}]),
  'tax-categories': base('Tax Categories','TAX_CATEGORY','taxCategoryCode','taxCategoryName',[{key:'companyId',label:'Company ID'},{key:'taxCategoryCode',label:'Category Code',required:true},{key:'taxCategoryName',label:'Category Name',required:true}]),
  'tax-codes': base('Tax Codes','TAX_CODE','taxCode','taxName',[{key:'companyId',label:'Company ID'},{key:'taxCode',label:'Tax Code',required:true},{key:'taxName',label:'Tax Name',required:true},{key:'taxType',label:'Tax Type',required:true},{key:'rate',label:'Rate',required:true,type:'number'}]),
  'change-requests': base('Master Change Requests','MASTER_DATA_CHANGE_REQUEST','recordId','reason',[{key:'enterpriseObjectId',label:'Enterprise Object ID',required:true},{key:'recordId',label:'Record ID'},{key:'changeType',label:'Change Type',required:true},{key:'reason',label:'Reason',required:true}])
};

const itemTabs = ['General','Classification','UOM','Planning','Procurement','Sales','Inventory','Manufacturing','Quality','Costing placeholder','Attachments placeholder','Audit'];
const partnerTabs = ['General','Customer','Supplier','Addresses','Contacts','Payment and Credit','Tax','Price List','Attachments placeholder','Audit'];

export function MasterDataPage({ resource }: { resource: string }) {
  const config = configs[resource];
  if (!config) return null;
  const tabs = resource === 'items' ? itemTabs : resource === 'business-partners' ? partnerTabs : [];
  return <div>
    {tabs.length ? <div className="overflow-x-auto border-b border-ink/10 bg-white px-5 pt-3 dark:bg-graphite"><div className="flex min-w-max gap-1">{tabs.map((tab, index) => <button key={tab} className={`rounded-t px-3 py-2 text-xs font-medium ${index === 0 ? 'bg-signal text-white' : 'text-steel'}`}>{tab}</button>)}</div></div> : null}
    <FoundationList title={config.title} subtitle={`DBA-004 ${config.title.toLowerCase()} master records with tenant-aware archive and audit behavior.`} endpoint={`/api/v1/master-data/${resource}`} objectCode={config.objectCode} columns={[{key:config.code,label:'Code / Identifier'},{key:config.name,label:'Name / Description'},{key:'status',label:'Status'}]} fields={config.fields} wrapData />
  </div>;
}
