export interface MasterResourceConfig {
  delegate: string;
  objectCode: string;
  codeField: string;
  nameField: string;
  fields: readonly string[];
  scope: 'GLOBAL' | 'GLOBAL_OR_TENANT' | 'TENANT';
  company: 'NONE' | 'OPTIONAL' | 'REQUIRED';
  dna?: string;
  hierarchyParent?: string;
  softDelete?: boolean;
  searchable?: boolean;
}

const common = ['status', 'isActive', 'effectiveFrom', 'effectiveTo'] as const;

export const MASTER_RESOURCES: Readonly<Record<string, MasterResourceConfig>> = {
  countries: { delegate: 'country', objectCode: 'COUNTRY', codeField: 'countryCode', nameField: 'countryName', scope: 'GLOBAL', company: 'NONE', dna: 'CTY', fields: ['countryCode','countryName','isoAlpha2','isoAlpha3','numericCode','phoneCode','defaultCurrencyId','taxRegionCode','timezoneGroup',...common] },
  states: { delegate: 'state', objectCode: 'STATE', codeField: 'stateCode', nameField: 'stateName', scope: 'GLOBAL', company: 'NONE', fields: ['countryId','stateCode','stateName',...common] },
  cities: { delegate: 'city', objectCode: 'CITY', codeField: 'cityCode', nameField: 'cityName', scope: 'GLOBAL', company: 'NONE', fields: ['countryId','stateId','cityCode','cityName','postalCodePattern','status','isActive'] },
  territories: { delegate: 'territory', objectCode: 'TERRITORY', codeField: 'territoryCode', nameField: 'territoryName', scope: 'TENANT', company: 'OPTIONAL', dna: 'TER', hierarchyParent: 'parentTerritoryId', fields: ['companyId','parentTerritoryId','territoryCode','territoryName','territoryType','countryId','stateId','cityId','hierarchyPath','hierarchyLevel',...common] },
  addresses: { delegate: 'address', objectCode: 'ADDRESS', codeField: 'addressLine1', nameField: 'addressLine1', scope: 'TENANT', company: 'OPTIONAL', fields: ['companyId','addressType','addressLine1','addressLine2','addressLine3','countryId','stateId','cityId','postalCode','phone','email','latitude','longitude','isPrimary','status','effectiveFrom','effectiveTo'] },
  contacts: { delegate: 'contactPerson', objectCode: 'CONTACT_PERSON', codeField: 'displayName', nameField: 'displayName', scope: 'TENANT', company: 'NONE', dna: 'CON', fields: ['firstName','middleName','lastName','displayName','designation','department','email','phone','mobile','preferredLanguage','preferredChannel','isPrimary','status','isActive'] },
  uom: { delegate: 'unitOfMeasure', objectCode: 'UNIT_OF_MEASURE', codeField: 'uomCode', nameField: 'uomName', scope: 'GLOBAL_OR_TENANT', company: 'NONE', dna: 'UOM', fields: ['uomCode','uomName','uomCategory','symbol','decimalPrecision','roundingRule','isBaseUom','status','isActive'] },
  'uom-conversions': { delegate: 'uomConversion', objectCode: 'UOM_CONVERSION', codeField: 'fromUomId', nameField: 'toUomId', scope: 'GLOBAL_OR_TENANT', company: 'NONE', searchable: false, fields: ['itemId','fromUomId','toUomId','conversionFactor','roundingMethod','effectiveFrom','effectiveTo','status'] },
  'item-groups': { delegate: 'itemGroup', objectCode: 'ITEM_GROUP', codeField: 'itemGroupCode', nameField: 'itemGroupName', scope: 'TENANT', company: 'OPTIONAL', dna: 'IGR', hierarchyParent: 'parentItemGroupId', fields: ['companyId','parentItemGroupId','itemGroupCode','itemGroupName','description','hierarchyPath','hierarchyLevel',...common] },
  'item-categories': { delegate: 'itemCategory', objectCode: 'ITEM_CATEGORY', codeField: 'itemCategoryCode', nameField: 'itemCategoryName', scope: 'TENANT', company: 'OPTIONAL', dna: 'ICA', hierarchyParent: 'parentItemCategoryId', fields: ['companyId','parentItemCategoryId','itemCategoryCode','itemCategoryName','categoryType','hierarchyPath','hierarchyLevel','status','isActive'] },
  'item-attributes': { delegate: 'itemAttributeDefinition', objectCode: 'ITEM_ATTRIBUTE_DEFINITION', codeField: 'attributeCode', nameField: 'attributeName', scope: 'TENANT', company: 'NONE', fields: ['attributeCode','attributeName','dataType','unitOfMeasureId','isRequired','isVariantAttribute','allowedValues','validationRule','status'] },
  'item-attribute-values': { delegate: 'itemAttributeValue', objectCode: 'ITEM_ATTRIBUTE_VALUE', codeField: 'itemId', nameField: 'attributeDefinitionId', scope: 'GLOBAL', company: 'NONE', searchable: false, fields: ['itemId','attributeDefinitionId','textValue','numberValue','dateValue','booleanValue','optionValue'] },
  brands: { delegate: 'brand', objectCode: 'BRAND', codeField: 'brandCode', nameField: 'brandName', scope: 'GLOBAL_OR_TENANT', company: 'NONE', dna: 'BRD', fields: ['brandCode','brandName','manufacturerId','status','isActive'] },
  manufacturers: { delegate: 'manufacturer', objectCode: 'MANUFACTURER', codeField: 'manufacturerCode', nameField: 'manufacturerName', scope: 'TENANT', company: 'NONE', dna: 'MFR', fields: ['manufacturerCode','manufacturerName','countryId','website','status','isActive'] },
  items: { delegate: 'item', objectCode: 'ITEM', codeField: 'itemCode', nameField: 'name', scope: 'TENANT', company: 'REQUIRED', dna: 'ITM', softDelete: true, fields: ['companyId','sku','itemCode','name','shortName','description','itemType','itemGroupId','itemCategoryId','brandId','manufacturerId','uom','baseUomId','purchaseUomId','salesUomId','stockUomId','manufacturingStrategy','replenishmentPolicy','valuationMethod','costingMethod','trackingMethod','isStockItem','isPurchaseItem','isSalesItem','isManufacturedItem','isSubcontractedItem','isBatchManaged','isSerialManaged','isQualityInspectionRequired','isMaintenanceSpare','shelfLifeDays','leadTimeDays','safetyStockQuantity','minimumOrderQuantity','maximumOrderQuantity','reorderLevel','reorderPoint','reorderQuantity','defaultWarehouseId','defaultSupplierId','taxCategoryId','standardCost','weight','weightUomId','volume','volumeUomId','barcode','hsCode','countryOfOriginId','status','approvalStatus','isActive','effectiveFrom','effectiveTo'] },
  warehouses: { delegate: 'warehouse', objectCode: 'WAREHOUSE', codeField: 'code', nameField: 'name', scope: 'TENANT', company: 'REQUIRED', dna: 'WHS', hierarchyParent: 'parentWarehouseId', softDelete: true, fields: ['companyId','branchId','plantId','locationId','parentWarehouseId','code','name','warehouseType','hierarchyPath','hierarchyLevel','isVirtual','allowsNegativeStock','defaultStockStatusId','status','isActive','effectiveFrom','effectiveTo'] },
  'warehouse-zones': { delegate: 'warehouseZone', objectCode: 'WAREHOUSE_ZONE', codeField: 'zoneCode', nameField: 'zoneName', scope: 'TENANT', company: 'NONE', dna: 'WHZ', hierarchyParent: 'parentZoneId', fields: ['warehouseId','parentZoneId','zoneCode','zoneName','zoneType','hierarchyPath','hierarchyLevel','temperatureMin','temperatureMax','status','isActive'] },
  bins: { delegate: 'bin', objectCode: 'BIN', codeField: 'binCode', nameField: 'binName', scope: 'TENANT', company: 'NONE', dna: 'BIN', fields: ['warehouseId','warehouseZoneId','parentBinId','binCode','binName','binType','capacityQuantity','capacityUomId','weightCapacity','volumeCapacity','isPickable','isReceivable','isBlocked','status','isActive'] },
  'stock-statuses': { delegate: 'stockStatus', objectCode: 'STOCK_STATUS', codeField: 'statusCode', nameField: 'statusName', scope: 'GLOBAL_OR_TENANT', company: 'NONE', fields: ['statusCode','statusName','availableForSale','availableForProduction','availableForTransfer','requiresApprovalToRelease','status','isActive'] },
  batches: { delegate: 'batch', objectCode: 'BATCH', codeField: 'batchNumber', nameField: 'batchNumber', scope: 'TENANT', company: 'REQUIRED', fields: ['companyId','itemId','batchNumber','manufacturingDate','expiryDate','supplierBatchNumber','qualityStatus','stockStatusId','status','isActive'] },
  'serial-numbers': { delegate: 'serialNumber', objectCode: 'SERIAL_NUMBER', codeField: 'serialNumber', nameField: 'serialNumber', scope: 'TENANT', company: 'REQUIRED', fields: ['companyId','itemId','serialNumber','batchId','manufacturerSerialNumber','warrantyStartDate','warrantyEndDate','currentWarehouseId','currentBinId','stockStatusId','lifecycleStatus','status','isActive'] },
  'business-partners': { delegate: 'businessPartner', objectCode: 'BUSINESS_PARTNER', codeField: 'partnerCode', nameField: 'partnerName', scope: 'TENANT', company: 'OPTIONAL', dna: 'BPR', softDelete: true, fields: ['companyId','partnerCode','partnerName','legalName','partnerType','registrationNumber','taxRegistrationNumber','countryId','defaultCurrencyId','paymentTermId','creditTermId','priceListId','territoryId','status','approvalStatus','isActive','effectiveFrom','effectiveTo'] },
  'customer-groups': { delegate: 'customerGroup', objectCode: 'CUSTOMER_GROUP', codeField: 'customerGroupCode', nameField: 'customerGroupName', scope: 'TENANT', company: 'OPTIONAL', hierarchyParent: 'parentCustomerGroupId', fields: ['companyId','parentCustomerGroupId','customerGroupCode','customerGroupName','hierarchyPath','hierarchyLevel','status','isActive'] },
  'supplier-groups': { delegate: 'supplierGroup', objectCode: 'SUPPLIER_GROUP', codeField: 'supplierGroupCode', nameField: 'supplierGroupName', scope: 'TENANT', company: 'OPTIONAL', hierarchyParent: 'parentSupplierGroupId', fields: ['companyId','parentSupplierGroupId','supplierGroupCode','supplierGroupName','hierarchyPath','hierarchyLevel','status','isActive'] },
  customers: { delegate: 'customer', objectCode: 'CUSTOMER', codeField: 'code', nameField: 'name', scope: 'GLOBAL', company: 'REQUIRED', fields: ['companyId','code','name','email','phone','creditLimit','businessPartnerId','customerGroupId','creditProfileId','salesTerritoryId','accountManagerUserId','defaultDeliveryAddressId','defaultBillingAddressId','defaultContactPersonId','status','isActive'] },
  suppliers: { delegate: 'supplier', objectCode: 'SUPPLIER', codeField: 'code', nameField: 'name', scope: 'GLOBAL', company: 'REQUIRED', fields: ['companyId','code','name','email','phone','paymentTerms','businessPartnerId','supplierGroupId','supplierRating','defaultPurchaseCurrencyId','defaultPaymentTermId','defaultAddressId','defaultContactPersonId','approvedSupplierStatus','status','isActive'] },
  'partner-addresses': { delegate: 'businessPartnerAddress', objectCode: 'BUSINESS_PARTNER_ADDRESS', codeField: 'businessPartnerId', nameField: 'addressRole', scope: 'GLOBAL', company: 'NONE', searchable: false, fields: ['businessPartnerId','addressId','addressRole','isDefault','effectiveFrom','effectiveTo'] },
  'partner-contacts': { delegate: 'businessPartnerContact', objectCode: 'BUSINESS_PARTNER_CONTACT', codeField: 'businessPartnerId', nameField: 'contactRole', scope: 'GLOBAL', company: 'NONE', searchable: false, fields: ['businessPartnerId','contactPersonId','contactRole','isDefault','effectiveFrom','effectiveTo'] },
  'payment-terms': { delegate: 'paymentTerm', objectCode: 'PAYMENT_TERM', codeField: 'paymentTermCode', nameField: 'paymentTermName', scope: 'GLOBAL_OR_TENANT', company: 'NONE', fields: ['paymentTermCode','paymentTermName','dueDays','dueDateCalculation','discountDays','discountPercentage','installmentDefinition','status','isActive'] },
  'credit-terms': { delegate: 'creditTerm', objectCode: 'CREDIT_TERM', codeField: 'creditTermCode', nameField: 'creditTermName', scope: 'TENANT', company: 'NONE', fields: ['creditTermCode','creditTermName','creditDays','graceDays','creditLimitRequired','overdueBlockPolicy','status','isActive'] },
  'credit-profiles': { delegate: 'creditProfile', objectCode: 'CREDIT_PROFILE', codeField: 'businessPartnerId', nameField: 'businessPartnerId', scope: 'TENANT', company: 'REQUIRED', searchable: false, fields: ['companyId','businessPartnerId','creditTermId','creditLimit','temporaryCreditLimit','temporaryLimitExpiry','overdueToleranceDays','autoBlockOnLimit','autoBlockOnOverdue','approvalRequiredForOverride','riskRating','status','effectiveFrom','effectiveTo'] },
  'delivery-terms': { delegate: 'deliveryTerm', objectCode: 'DELIVERY_TERM', codeField: 'deliveryTermCode', nameField: 'deliveryTermName', scope: 'GLOBAL_OR_TENANT', company: 'NONE', fields: ['deliveryTermCode','deliveryTermName','description','status','isActive'] },
  incoterms: { delegate: 'incoterm', objectCode: 'INCOTERM', codeField: 'incotermCode', nameField: 'incotermName', scope: 'GLOBAL', company: 'NONE', fields: ['incotermCode','incotermName','versionYear','description','status','isActive'] },
  'price-lists': { delegate: 'priceList', objectCode: 'PRICE_LIST', codeField: 'priceListCode', nameField: 'priceListName', scope: 'TENANT', company: 'OPTIONAL', fields: ['companyId','priceListCode','priceListName','currencyId','priceListType','effectiveFrom','effectiveTo','taxInclusive','status','isActive'] },
  'tax-categories': { delegate: 'taxCategory', objectCode: 'TAX_CATEGORY', codeField: 'taxCategoryCode', nameField: 'taxCategoryName', scope: 'TENANT', company: 'OPTIONAL', fields: ['companyId','taxCategoryCode','taxCategoryName','description','status','isActive'] },
  'tax-codes': { delegate: 'taxCode', objectCode: 'TAX_CODE', codeField: 'taxCode', nameField: 'taxName', scope: 'TENANT', company: 'OPTIONAL', fields: ['companyId','taxCode','taxName','taxCategoryId','countryId','taxType','rate','recoverablePercentage','payableAccountId','receivableAccountId','effectiveFrom','effectiveTo','status','isActive'] },
  'change-requests': { delegate: 'masterDataChangeRequest', objectCode: 'MASTER_DATA_CHANGE_REQUEST', codeField: 'recordId', nameField: 'reason', scope: 'TENANT', company: 'NONE', fields: ['enterpriseObjectId','recordId','changeType','requestedChanges','reason','approvalStatus','workflowInstanceId'] },
  'duplicate-rules': { delegate: 'duplicateDetectionRule', objectCode: 'DUPLICATE_DETECTION_RULE', codeField: 'ruleCode', nameField: 'ruleName', scope: 'TENANT', company: 'NONE', fields: ['enterpriseObjectId','ruleCode','ruleName','matchFields','threshold','action','status','isActive'] }
};

export function masterResource(resource: string): MasterResourceConfig | undefined {
  return MASTER_RESOURCES[resource];
}
